CONFIG -= rtti
QMAKE_CFLAGS_RELEASE = /O2 /Ot -MD -Zi /GR-
QMAKE_CXXFLAGS_EXCEPTIONS_ON =
QMAKE_CXXFLAGS_STL_ON = 
QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO += /Od -MD -Zi
QMAKE_LFLAGS_RELEASE = /INCREMENTAL:NO /DEBUG /OPT:REF /OPT:ICF
DEFINES   += QT_NO_GESTURES